# @url = 
@url = http://localhost:3000

## USUARIOS
POST {{url}}/registro
Content-Type: application/json

{
    "nick": "Adrian",
    "nombreCuenta": "soyIcaruk",
    "email": "adrian@gmail.com",
    "password": "12345678",
    "biografia": "Full Stack Developer",
    "avatar": "https://imgur.com/AxWdS6U.png",
    "pais": "España",
    "ciudad": "Valencia"
}

###
# @name resLogin
POST {{url}}/login
Content-Type: application/json

{
    "email": "adrian@gmail.com",
    "password": "12345678"
}


###
@token = {{resLogin.response.body.token}}

POST {{url}}/logout
Authorization: {{token}}
###

DELETE {{url}}/delete
Authorization: {{token}}
###

POST {{url}}/post
Content-Type: application/json
Authorization: {{token}}

{
    "mensaje": "Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}
###

POST {{url}}/getPosts
Content-Type: application/json
Authorization: {{token}}
###

POST {{url}}/getMisPost
Content-Type: application/json
Authorization: {{token}}
###

DELETE {{url}}/borrarPost
Content-Type: application/json
Authorization: {{token}}
