# @url = 
@url = http://localhost:3000

## USUARIOS
POST {{url}}/registro
Content-Type: application/json

{
    "nick": "Rosa",
    "nombreCuenta": "soyRosa",
    "email": "rosa@gmail.com",
    "password": "12345678",
    "biografia": "Full Stack Developer",
    "avatar": "https://1.bp.blogspot.com/-79DdxzZkDog/T76QV6v5IuI/AAAAAAAAAEY/6DzpGZzsmfA/s320/homerocatolico_456_336.jpg",
    "pais": "España",
    "ciudad": "Valencia"
}

###
# @name resLogin
POST {{url}}/login
Content-Type: application/json

{
    "email": "rosa@gmail.com",
    "password": "12345678"
}


###
@token = {{resLogin.response.body.token}}

POST {{url}}/logout
Authorization: {{token}}
###

DELETE {{url}}/delete
Authorization: {{token}}
###